#!/usr/bin/env python3
"""Generate colors_generated.lua from three per-display JSON palette files."""

import sys
import json
import datetime

TN = {
    "black": "0xff1a1b26", "white": "0xffc0caf5",
    "red": "0xfff7768e", "green": "0xff9ece6a",
    "blue": "0xff7aa2f7", "yellow": "0xffe0af68",
    "orange": "0xffff9e64", "magenta": "0xffbb9af7",
    "grey": "0xff565f89",
    "bg1": "0xff1f2335", "bg2": "0xff24283b",
    "bar_bg": "0x001a1b26", "bar_border": "0xff292e42",
    "popup_bg": "0xc01f2335", "popup_border": "0xff565f89",
    "accent": "0xff7aa2f7",
}


def load(path):
    try:
        with open(path) as f:
            d = json.load(f)
        return d or {}
    except Exception:
        return {}


def g(p, k):
    return p.get(k) or TN.get(k, "0xff000000")


def main(p1_path, p2_path, p3_path, out_path):
    palettes = [load(p) for p in [p1_path, p2_path, p3_path]]
    gp = palettes[0]

    def disp(p):
        return {k: g(p, k) for k in ("accent", "bg1", "bg2")}

    d = [disp(p) for p in palettes]
    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lua = (
        f"-- Auto-generated by theme/generate.sh — do not edit manually\n"
        f"-- Generated: {ts}\n"
        f"local with_alpha = function(color, alpha)\n"
        f"  if alpha > 1.0 or alpha < 0.0 then return color end\n"
        f"  return (color & 0x00ffffff) | (math.floor(alpha * 255.0) << 24)\n"
        f"end\n\n"
        f"return {{\n"
        f"  black      = {g(gp, 'black')},\n"
        f"  white      = {g(gp, 'white')},\n"
        f"  red        = {g(gp, 'red')},\n"
        f"  green      = {g(gp, 'green')},\n"
        f"  blue       = {g(gp, 'blue')},\n"
        f"  yellow     = {g(gp, 'yellow')},\n"
        f"  orange     = {g(gp, 'orange')},\n"
        f"  magenta    = {g(gp, 'magenta')},\n"
        f"  grey       = {g(gp, 'grey')},\n"
        f"  transparent = 0x00000000,\n\n"
        f"  bar = {{\n"
        f"    bg     = {g(gp, 'bar_bg')},\n"
        f"    border = {g(gp, 'bar_border')},\n"
        f"  }},\n"
        f"  popup = {{\n"
        f"    bg     = {g(gp, 'popup_bg')},\n"
        f"    border = {g(gp, 'popup_border')},\n"
        f"  }},\n"
        f"  bg1 = {g(gp, 'bg1')},\n"
        f"  bg2 = {g(gp, 'bg2')},\n\n"
        f"  -- Per-display accent/bg tones (from each monitor's wallpaper)\n"
        f"  display = {{\n"
        f"    [1] = {{ accent = {d[0]['accent']}, bg1 = {d[0]['bg1']}, bg2 = {d[0]['bg2']} }},\n"
        f"    [2] = {{ accent = {d[1]['accent']}, bg1 = {d[1]['bg1']}, bg2 = {d[1]['bg2']} }},\n"
        f"    [3] = {{ accent = {d[2]['accent']}, bg1 = {d[2]['bg1']}, bg2 = {d[2]['bg2']} }},\n"
        f"  }},\n\n"
        f"  with_alpha = with_alpha,\n"
        f"}}\n"
    )

    with open(out_path, "w") as f:
        f.write(lua)
    print(f"Generated: {out_path}")


if __name__ == "__main__":
    if len(sys.argv) != 5:
        print("Usage: generate_lua.py d1.json d2.json d3.json output.lua", file=sys.stderr)
        sys.exit(1)
    main(sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4])
