-- Auto-generated by theme/generate.sh — do not edit manually
-- Generated: 2026-06-26 01:20:08
local with_alpha = function(color, alpha)
  if alpha > 1.0 or alpha < 0.0 then return color end
  return (color & 0x00ffffff) | (math.floor(alpha * 255.0) << 24)
end

return {
  black      = 0xff060a0b,
  white      = 0xffd2dde0,
  red        = 0xff843d24,
  green      = 0xff299929,
  blue       = 0xff294e99,
  yellow     = 0xff998f29,
  orange     = 0xff8e4b2a,
  magenta    = 0xff8f2999,
  grey       = 0xff6d7274,
  transparent = 0x00000000,

  bar = {
    bg     = 0x00060a0b,
    border = 0xff535b55,
  },
  popup = {
    bg     = 0xc03d433f,
    border = 0xff6d7274,
  },
  bg1 = 0xff3d433f,
  bg2 = 0xff535b55,

  -- Per-display accent/bg tones (from each monitor's wallpaper)
  display = {
    [1] = { accent = 0xffd39254, bg1 = 0xff3d433f, bg2 = 0xff535b55 },
    [2] = { accent = 0xffd39254, bg1 = 0xff3d433f, bg2 = 0xff535b55 },
    [3] = { accent = 0xffd39254, bg1 = 0xff3d433f, bg2 = 0xff535b55 },
  },

  with_alpha = with_alpha,
}
